HAS_MKL = yes 

# includes and libraries
VES3D_TEMPLATES = -I$(VES3D_DIR)/src
VES3D_INCLUDE   = -I$(VES3D_DIR)/include $(VES3D_TEMPLATES)
BLAS_INCLUDE    = -I/opt/intel/mkl/10.2.2.025/include
ALL_INCLUDE     = $(VES3D_INCLUDE) $(BLAS_INCLUDE) 

VES3D_LIBS = -L$(VES3D_DIR)/lib -lves3d 
BLAS_LIBS  = -L/opt/intel/Compiler/11.1/059/mkl/lib/em64t 		\
	-Wl,--start-group -lmkl_intel_lp64 -lmkl_intel_thread		\
	-lmkl_core -Wl,--end-group

LDFLAGS  = $(VES3D_LIBS) $(BLAS_LIBS) -lpthread 