MAKE_DEP += ${VES3D_MKDIR}/makefile.octane

COMPILER_VENDOR = gnu
include ${VES3D_MKDIR}/makefile.default

# customization ##########################################
VES3D_DEBUG     = yes
VES3D_PROFILE   = yes
VES3D_TESTING   = yes
VES3D_VERBOSE   = yes

# compiler
BLASPKG         = HAS_BLAS
BLAS_LIBS       = -framework vecLib
BLAS_INCLUDE    =
CXXFLAGS       += -D${BLASPKG} ${BLAS_INCLUDE}

# linker
LDFLAGS        +=
LDLIBS         += $(BLAS_LIBS) -lpthread
