# Flags
ARFLAGS = -r
CXXFLAGS= -fopenmp -fPIC -fno-exceptions -pedantic

ifeq ($(VES3D_TESTING),yes)
  CXXFLAGS+= -gstabs+ -O0 -DVERBOSE -DPROFILING #-DNDEBUG #-msse3
else
  CXXFLAGS+= -O3 -finline-functions -unroll-loops  			\
    #-DPROFILING #-msse3 #-malign-double
endif










































