# Flags
ARFLAGS = -r
CXXFLAGS= -fopenmp -fPIC -fno-exceptions -w

ifeq ($(VES3D_TESTING),yes)
  CXXFLAGS+=  -O0 -g  -pedantic -DVERBOSE -DPROFILING #-gstabs+
else
  CXXFLAGS+= -O3 -finline-functions -funroll-loops -w  			\
  	     -funsafe-loop-optimizations -DNDEBUG -msse3 #-malign-double
endif

COMPILER_VENDOR=GNU
