void DotProductGpu(const float *a, const float *b, int stride, int num_surfs, float *aDb);
void CrossProductGpu(const float *a, const float *b, int stride, int num_surfs, float *aCb);
void xvpwGpu(const float *x, const float *a, const float *y, int stride, int num_surfs, float *AxPy);
void xvpbGpu(const float *x, const float *a, float y, int stride, int num_surfs, float *AxPy);
void uyInvGpu(const float *x, const float *y, int stride, int num_surfs, float *xDy);
void SqrtGpu(const float* x_in, int length, float *x_out);
void InvGpu(const float* x_in, int length, float *x_out);
void xyGpu(const float* x_in, const float *y_in, int length, float *xy_out);
void xyInvGpu(const float* x_in, const float *y_in, int length, float *xDy_out);
void ReduceGpu(const float *x_in, const int x_dim, const float *w_in, const float *q_in, int stride, int num_surfs, float *int_x_dw);
void CircShiftGpu(const float *arr_in, int n_vecs, int vec_length, int shift, float *arr_out);
void axpyGpu(float a, const float* x_in, const float *y_in, int length, float *axpy_out);
void axpbGpu(float a, const float* x_in, float b, int length, float *axpb_out);
void cuda_shuffle(float *in, int stride, int n_surfs, int dim, float *out);
void cuda_stokes(int m, int n, int t_head, int t_tail, const float *T, const float *S, const float *D, float *U, const float *Q);
void ResampleGpu(int p, int n_funs, int q, const float *shc_p, float *shc_q);
void ScaleFreqsGpu(int p, int n_funs, const float *shc_in, const float *alpha, float *shc_out);
void avpwGpu(const float *a_in, const float *v_in, const float *w_in, int stride, int num_surfs, float *avpw_out);
void avpwGpu(const float *a_in, const float *v_in, int stride, int num_surfs, float *avpw_out);
float maxGpu(float *in, int n);
float AlgebraicDotGpu(const float *x, const float *y, size_t length);
void axGpu(const float* a, const float* x, size_t stride, size_t n_vecs, float* ax_out);
void apxGpu(const float *a_in, const float *x_in, int stride, int n_subs, float *apx_out);

void DotProductGpu(const double *a, const double *b, int stride, int num_surfs, double *aDb);
void CrossProductGpu(const double *a, const double *b, int stride, int num_surfs, double *aCb);
void xvpwGpu(const double *x, const double *a, const double *y, int stride, int num_surfs, double *AxPy);
void xvpbGpu(const double *x, const double *a, double y, int stride, int num_surfs, double *AxPy);
void uyInvGpu(const double *x, const double *y, int stride, int num_surfs, double *xDy);
void SqrtGpu(const double* x_in, int length, double *x_out);
void InvGpu(const double* x_in, int length, double *x_out);
void xyGpu(const double* x_in, const double *y_in, int length, double *xy_out);
void xyInvGpu(const double* x_in, const double *y_in, int length, double *xDy_out);
void ReduceGpu(const double *x_in, const int x_dim, const double *w_in, const double *q_in, int stride, int num_surfs, double *int_x_dw);
void CircShiftGpu(const double *arr_in, int n_vecs, int vec_length, int shift, double *arr_out);
void axpyGpu(double a, const double* x_in, const double *y_in, int length, double *axpy_out);
void axpbGpu(double a, const double* x_in, double b, int length, double *axpb_out);
void cuda_shuffle(double *in, int stride, int n_surfs, int dim, double *out);
void cuda_stokes(int m, int n, int t_head, int t_tail, const double *T, const double *S, const double *D, double *U, const double *Q);
void ResampleGpu(int p, int n_funs, int q, const double *shc_p, double *shc_q);
void ScaleFreqsGpu(int p, int n_funs, const double *shc_in, const double *alpha, double *shc_out);
void avpwGpu(const double *a_in, const double *v_in, const double *w_in, int stride, int num_surfs, double *avpw_out);
void avpwGpu(const double *a_in, const double *v_in, int stride, int num_surfs, double *avpw_out);
double maxGpu(double *in, int n);
double AlgebraicDotGpu(const double *x, const double *y, size_t length);
void axGpu(const double* a, const double* x, size_t stride, size_t n_vecs, double* ax_out);
void apxGpu(const double *a_in, const double *x_in, int stride, int n_subs, double *apx_out);

#include "transpose_kernel.h"
